### PR TITLE
Update for Meteor 1.3.

### PR DESCRIPTION
**Pull request by benjamn**
Note that Meteor 1.2-compatible versions of this package can still be published on the 0.3.x version line using the 1.2 version of the Meteor command-line tool.

If there are any important differences between the Node version of `util` and the npm `util` package, I encourage you to fix them in `client.js`.

### CODE REVIEW

**Comment by mitar** [comment]
The issue is that that NPM module is old, unmaintained, and not in sync anymore with node.js. I do not want to [constantly have to fix the module on my side](https://github.com/defunctzombie/node-util/pull/12/files).

Now, I can worry about that and manually maintain that package. Or I just take files from node.js. I prefer the second option because then I can update to new util code just by updating the git submodule.

**Comment by mitar** [comment]
So concretely, I didn't go with NPM package to begin with because it does not look like a good package. This is why I went with all this complications with node.js submodule to get it to work for real. This pull request is requesting that I go back to consider that package, which for me changes the whole purpose of this package: providing real and up-to-date `util` on the client side, which is exactly the same as what users get when they do `Npm.require('util')` on the server. :-(

**Comment by benjamn** [comment]
Whether or not you use `util` from npm or copy it from the Node repo is an independent decision. The reason `peerlibrary:util` is broken in Meteor 1.3 is that your partial implementation of `require` has been replaced by a different (full) implementation of `require`. There are plenty of other ways to fix that conflict, such as copying `util.js` from Node and modifying it in a few small ways to avoid the need for a custom `require` implementation.

**Comment by mitar** [comment]
Yes, but with my custom `require` I do not have to copy anything, I just keep the same file as upstream. You do understand that this is much easier to maintain.

The issue for me is that you changed behavior of the `ecmascript` package between Meteor 1.2 and 1.3 in a backwards incompatible way. This is for me a regression. Now, I can stop using the code which worked before and switch to NPM module, I can start modifying the code manually to make it work with Meteor 1.3, or Meteor can provide a backwards compatible package to which I can switch. I prefer the last option. In general I see this as a consequence of packages which do too many things at once. Why not having a package which just compiles ES2016, and then package which integrates it with the rest, and then package which makes a nice imply-bundle for common use case?

**Comment by benjamn** [comment]
Absolute backwards compatibility would be deadly for Meteor in the long run. Unless I'm mistaken, the only sense in which Meteor 1.3 was backwards incompatible for you was that it interfered with your custom implementation of `require`. If we can fix that relatively minor incompatibility, then your problem will be solved, and I think you'll be less attracted to the idea of preserving the incomplete 1.2 behavior of the `ecmascript` package.

**Comment by benjamn** [comment]
Here's another idea. Copy the `util.js` file from Node and _don't_ modify it. Instead, you can make Meteor's module system return something useful from `require("internal/util")` by including this code before `util.js` is evaluated:

``` js
meteorInstall({
  "..": { // This ".." refers to a global module namespace outside the app.
    node_modules: {
      internal: {
        "util.js": function(require, exports, module) {
          // Implement util.js however you like.
        }
      }
    }
  }
});
```

The `buffer` and `vm` dependencies should be provided by `meteor-node-stubs`, but feel free to implement them in a similar way if you have to.

**Comment by mitar** [comment]
OK, this is going a bit above my head. I do not understand anything about it. Do you have an example somewhere of somebody else doing something like this?

**Comment by benjamn** [comment]
[Here](https://github.com/meteor/node-stubs/blob/2d3849b8081eded7b96064d39f6d85eaf3d6e30c/index.js#L20-L27). I'll update the pull request.

**Comment by benjamn** [comment]
Good news: if you use the same version of `lib/util.js` that is available on the server in Meteor 1.3 (which seems like a good idea?), then you don't need to provide any manual `require` exceptions. See 4c4adad0444cb53ff2b48e7ba9d65762970d6f9b above.

**Comment by mitar** [comment]
But isn't Meteor upgrading to new node version? This is the whole point of using git submodule, to be able to easily upgrade as Meteor upgrades. :-)

**Comment by mitar** [comment]
But you are right, I should have used the same version until now.

**Comment by mitar** [comment]
I have changed it differently: 09840db50fd8caebb25699afe5ecd6653202d6f0

Thanks for all the help with understanding what is happening here.

**Pull request closed without merging**
